"""Clock synchronization with a KDC and automatic-NTP bookkeeping."""

import json
import shutil
import subprocess
import time
from datetime import datetime, timezone

from . import paths
from .constants import SKEW_LIMIT
from .ui import YLW, R, err, info, ok, warn
from .utils import fmt_skew, out, valid_clock_epoch


def read_state():
    if paths.STATE_F and paths.STATE_F.exists():
        try:
            return json.loads(paths.STATE_F.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    return {}


def write_state(st):
    paths.ensure_system_storage()
    paths.atomic_write(paths.STATE_F, json.dumps(st, indent=2) + "\n", mode=0o600)


def ntp_enabled():
    return "yes" in out(["timedatectl", "show", "-p", "NTP", "--value"]).lower()


def set_ntp(enabled):
    """Enable or disable automatic NTP and report whether the operation succeeded."""
    try:
        result = subprocess.run(
            ["timedatectl", "set-ntp", "true" if enabled else "false"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
            text=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        err(f"Failed to {'enable' if enabled else 'disable'} automatic NTP: {exc}")
        return False
    if result.returncode != 0:
        detail = result.stderr.strip() or f"exit status {result.returncode}"
        err(f"Failed to {'enable' if enabled else 'disable'} automatic NTP: {detail}")
        return False
    return True


def sync_clock(target_epoch, host, faketime=False):
    """Align the local clock to the KDC or generate a faketime wrapper."""
    if not valid_clock_epoch(target_epoch):
        err(f"Refusing invalid KDC timestamp from {host}: {target_epoch!r}")
        return False
    skew = target_epoch - time.time()
    if abs(skew) < 5:
        ok(f"Clock already aligned with {host} (delta {int(skew)}s)")
        return True
    print(f"    local clock is {YLW}{fmt_skew(skew)}{R} compared to the KDC")

    if faketime:
        if not shutil.which("faketime"):
            err("faketime is not installed")
            return False
        offset = f"{'+' if skew >= 0 else '-'}{abs(int(skew))}s"
        script = paths.BASE / "faketime.sh"
        paths.atomic_write(
            script,
            "#!/bin/sh\n"
            f"# generated by KRB_Handler for {host}\n"
            f"exec faketime -f '{offset}' \"$@\"\n",
            mode=0o700,
            owner_back=True,
        )
        ok(f"Wrapper created: {script}   (usage: {script} <your-tool> ...)")
        return True

    if abs(skew) < SKEW_LIMIT:
        info(f"{int(abs(skew))}s skew is within the limit ({SKEW_LIMIT}s) - syncing anyway")

    st = read_state()
    ntp_was_on = ntp_enabled()
    if ntp_was_on:
        st["ntp_was_on"] = True
        write_state(st)
        if not set_ntp(False):
            st.pop("ntp_was_on", None)
            write_state(st)
            return False
        info("Automatic NTP disabled so it does not undo the adjustment")
    else:
        write_state(st)

    stamp = datetime.fromtimestamp(target_epoch, timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    try:
        r = subprocess.run(
            ["date", "-u", "-s", stamp],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
            text=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        r = None
        failure = str(exc)
    if r is not None and r.returncode == 0:
        ok(f"Clock synced with the KDC ({stamp} UTC)")
        return True
    else:
        failure = failure if r is None else (r.stderr.strip() or f"exit status {r.returncode}")
        err(f"Failed to adjust the clock: {failure}")
        if ntp_was_on and set_ntp(True):
            st.pop("ntp_was_on", None)
            write_state(st)
            warn("Automatic NTP was re-enabled after the failed clock adjustment")
        return False


def restore_clock():
    st = read_state()
    if st.get("ntp_was_on"):
        if not set_ntp(True):
            return False
        st.pop("ntp_was_on", None)
        ok("Automatic NTP re-enabled")
    write_state(st)
    return True
