"""Render profile data into krb5.conf and the managed /etc/hosts block."""

from datetime import datetime, timezone

from .constants import HOSTS_BEGIN, HOSTS_END, SKEW_LIMIT
from .profiles import validate_profile


def render_krb5(prof):
    prof = validate_profile(prof)
    o = prof.get("options", {})
    lines = [
        "# Generated by KRB_Handler (Avocado / Caramelo Storm) - do not edit by hand.",
        f"# profile: {prof['name']}   {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        "",
        "[libdefaults]",
        f"    default_realm = {prof['default_realm']}",
        "    dns_lookup_realm = false",
        "    dns_lookup_kdc = false",
        "    rdns = false",
        "    dns_canonicalize_hostname = false",
        "    ticket_lifetime = 24h",
        "    renew_lifetime = 7d",
        "    forwardable = true",
        "    noaddresses = true",
        "    udp_preference_limit = 1",   # Force TCP because large PACs exceed UDP.
        f"    clockskew = {SKEW_LIMIT}",
    ]
    if o.get("weak_crypto"):
        lines += [
            "    allow_weak_crypto = true",
            "    default_tgs_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 rc4-hmac",
            "    default_tkt_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 rc4-hmac",
            "    permitted_enctypes  = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 rc4-hmac",
        ]
    lines += ["", "[realms]"]
    for realm in sorted(prof["realms"]):
        e = prof["realms"][realm]
        lines.append(f"    {realm} = {{")
        for kdc in e.get("kdc") or []:
            lines.append(f"        kdc = {kdc}")
        if e.get("kdc"):
            lines.append(f"        admin_server = {e['kdc'][0]}")
            lines.append(f"        kpasswd_server = {e['kdc'][0]}")
        lines.append(f"        default_domain = {realm.lower()}")
        lines.append("    }")
    lines += ["", "[domain_realm]"]
    for realm in sorted(prof["realms"]):
        dom = realm.lower()
        lines.append(f"    {dom} = {realm}")
        lines.append(f"    .{dom} = {realm}")
    # Each host maps to the longest matching realm suffix. Without this, a child
    # domain host may also match the parent suffix and the client will query the
    # wrong KDC, causing "KDC reply did not match expectations".
    for h in prof["hosts"]:
        best = best_realm_for(h["fqdn"], prof["realms"])
        if best:
            lines.append(f"    {h['fqdn']} = {best}")
    lines.append("")
    return "\n".join(lines)


def best_realm_for(fqdn, realms):
    """Return the realm whose domain is the most specific FQDN suffix."""
    match = ""
    for realm in realms:
        dom = realm.lower()
        if (fqdn == dom or fqdn.endswith("." + dom)) and len(dom) > len(match):
            match = dom
    return match.upper() if match else ""


def render_hosts_block(prof):
    prof = validate_profile(prof)
    lines = [f"{HOSTS_BEGIN}: {prof['name']} (generated; use krb-handler)"]
    for h in prof["hosts"]:
        names = " ".join([h["fqdn"], *h.get("aliases", [])])
        lines.append(f"{h['ip']}\t{names}")
    lines.append(HOSTS_END)
    return "\n".join(lines) + "\n"
